import dashboardpage from "../../support/Pages/Itera/dashboard.js";
const DashboardInputan = require("../../fixtures/Itera/dashboard.json");

Cypress.on("uncaught:exception", (err, runnable) => {
  return false;
});
describe("Edit & Search Customer Detail", () => {
  const DashboardPage = new dashboardpage();
  beforeEach(() => {
    cy.visit("/");
  });
  it("Cancel Edit Customer Detail", () => {
    //cy.get(DashboardPage.login).click();
    DashboardPage.Login();
    //cy.get(DashboardPage.username).type(DashboardInputan.validusername);
    DashboardPage.Username();
    //cy.get(DashboardPage.password).clear().type(DashboardInputan.pass);
    DashboardPage.Pass();
    //cy.get(DashboardPage.but_log).click();
    DashboardPage.But_log();
    //cy.get(DashboardPage.h1).should("contain.text", DashboardInputan.h1d);
    DashboardPage.H1d();
    //cy.get(DashboardPage.dashcustomer).click();
    DashboardPage.Dashcustomer();
    //cy.get(DashboardPage.h2).should("contain.text", DashboardInputan.h2e);
    DashboardPage.H2e();
    //cy.get(DashboardPage.company).clear().type(DashboardInputan.company);
    DashboardPage.Company();
    //cy.get(DashboardPage.address).clear().type(DashboardInputan.address);
    DashboardPage.Address();
    //cy.get(DashboardPage.city).clear().type(DashboardInputan.city);
    DashboardPage.City();
    //cy.get(DashboardPage.phone).clear().type(DashboardInputan.phone);
    DashboardPage.Phone();
    //cy.get(DashboardPage.email).clear().type(DashboardInputan.validemail);
    DashboardPage.Email();
    //cy.get(DashboardPage.backcustomerdetail).click();
    DashboardPage.Backcustomer();
    //cy.get(DashboardPage.h2).should("contain.text", DashboardInputan.h2dc);
    DashboardPage.H2dc;
  });
  it("Success Edit Customer Detail", () => {
    //cy.get(DashboardPage.login).click();
    DashboardPage.Login();
    //cy.get(DashboardPage.username).type(DashboardInputan.validusername);
    DashboardPage.Username();
    //cy.get(DashboardPage.password).clear().type(DashboardInputan.pass);
    DashboardPage.Pass();
    //cy.get(DashboardPage.but_log).click();
    DashboardPage.But_log();
    //cy.get(DashboardPage.h1).should("contain.text", DashboardInputan.h1d);
    DashboardPage.H1d();
    //cy.get(DashboardPage.dashcustomer).click();
    DashboardPage.Dashcustomer();
    //cy.get(DashboardPage.h2).should("contain.text", DashboardInputan.h2e);
    DashboardPage.H2e();
    //cy.get(DashboardPage.company).clear().type(DashboardInputan.company);
    DashboardPage.Company();
    //cy.get(DashboardPage.address).clear().type(DashboardInputan.address);
    DashboardPage.Address();
    //cy.get(DashboardPage.city).clear().type(DashboardInputan.city);
    DashboardPage.City();
    //cy.get(DashboardPage.phone).clear().type(DashboardInputan.phone);
    DashboardPage.Phone();
    //cy.get(DashboardPage.email).clear().type(DashboardInputan.validemail);
    DashboardPage.Email();
    //cy.get(DashboardPage.but_edit).click();
    DashboardPage.But_edit();
    //cy.get(DashboardPage.h2).should("contain.text", DashboardInputan.h2dc);
    DashboardPage.H2dc;
  });
  it("Success Search Detail Customer - Search by Email", () => {
    //cy.get(DashboardPage.login).click();
    DashboardPage.Login();
    //cy.get(DashboardPage.username).type(DashboardInputan.validusername);
    DashboardPage.Username();
    //cy.get(DashboardPage.password).clear().type(DashboardInputan.pass);
    DashboardPage.Pass();
    //cy.get(DashboardPage.but_log).click();
    DashboardPage.But_log();
    //cy.get(DashboardPage.h1).should("contain.text", DashboardInputan.h1d);
    DashboardPage.H1d();
    //cy.get(DashboardPage.search).type(DashboardInputan.validemail);
    DashboardPage.Validemail();
    //cy.get(DashboardPage.but_search).click();
    DashboardPage.But_search();
    //cy.get(DashboardPage.table1).should("contain.text", DashboardInputan.validemail);
    DashboardPage.Table1();
  });
  it("Failed Search Detail Customer - Wrong Email", () => {
    //cy.get(DashboardPage.login).click();
    DashboardPage.Login();
    //cy.get(DashboardPage.username).type(DashboardInputan.validusername);
    DashboardPage.Username();
    //cy.get(DashboardPage.password).clear().type(DashboardInputan.pass);
    DashboardPage.Pass();
    //cy.get(DashboardPage.but_log).click();
    DashboardPage.But_log();
    //cy.get(DashboardPage.h1).should("contain.text", DashboardInputan.h1d);
    DashboardPage.H1d();
    //cy.get(DashboardPage.search).type(DashboardInputan.invalidemail);
    DashboardPage.Invalidemail();
    //cy.get(DashboardPage.but_search).click();
    DashboardPage.But_search();
    //cy.get(DashboardPage.table2).should("contain.text", DashboardInputan.invalid);
    DashboardPage.Table2();
  });
});
